# Aiming for lots of linting
linters:
  enable:
    - gocritic
    - goimports
    - gosec
    - govet
    - misspell

linters-settings:
  gocritic:
    enabled-tags:
      # - diagnostic
      # - opinionated
      # - performance
      # - style
  goimports:
    local-prefixes: github.com/control-alt-repeat/control-alt-repeat
  govet:
    enable:
      - nilness
      - shadow
  misspell:
    locale: US
    ignore-words:
      - organisation
      - recognised
issues:
  exclude-rules:
    - text: 'shadow: declaration of "(err|ctx)" shadows declaration at'
      linters: [ govet ]

# Exclude the hostedtoolcache directory
exclude:
  - ../../../../../opt/hostedtoolcache/.*  # Adjust the path as needed based on your project structure

run:
  timeout: 5m
