name: Deploy Control Alt Repeat
on:
  pull_request:
  push:
    branches-ignore:
      - main
env:
  AWS_REGION : eu-west-2

permissions:
  id-token: write
  # Required: allow read access to the content for analysis.
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read
  # Optional: allow write access to checks to allow the action to annotate code in the PR.
  checks: write

jobs:
  checkout-source-code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Create temporary directory and archive source code
        run: |
          # Create a temporary directory
          TEMP_DIR=$(mktemp -d)

          # Copy files to the temporary directory
          cp -r . "$TEMP_DIR"

          # Create a tar archive from the temporary directory
          tar -czf source-code.tar.gz -C "$TEMP_DIR" .

          # Clean up the temporary directory
          rm -rf "$TEMP_DIR"
      - name: Upload source code as artifact
        uses: actions/upload-artifact@v4
        with:
          name: source-code
          path: source-code.tar.gz

  lint-golang:
    needs: checkout-source-code
    uses: ./.github/workflows/lint-golang.yaml
    secrets: inherit

  lint-terraform:
    needs: checkout-source-code
    uses: ./.github/workflows/lint-terraform.yaml
    secrets: inherit
 
  main-pipeline:
    runs-on: ubuntu-latest
    needs:
      - lint-golang
      - lint-terraform
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.7
      - name: Download source code artifact
        uses: actions/download-artifact@v4
        with:
          name: source-code

      - name: Extract source code
        run: tar -xzf source-code.tar.gz
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubOIDC
          aws-region: eu-west-2
          role-session-name: OIDCRoleSessions

      - run: ./scripts/build-lambda-functions.sh

      - run: terraform fmt -check

      - run: terraform init
        working-directory: configs/test
      - run: terraform validate -no-color
        working-directory: configs/test

      - run: terraform init
        working-directory: configs/live
      - run: terraform validate -no-color
        working-directory: configs/live