name: Golang CI Sec

on:
  workflow_call:

jobs:
  go-sec:
    runs-on: ubuntu-latest
    steps:
      - name: Download source code artifact
        uses: actions/download-artifact@v3
        with:
          name: source-code

      - name: Extract source code
        run: tar -xzf source-code.tar.gz

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
          cache: true

      - name: Cache gosec
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/bin/gosec
          key: ${{ runner.os }}-gosec-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-gosec-

      - name: Install gosec
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          gosec --version

      - name: Run gosec
        run: gosec ./...
