name: Golang CI Vet

on:
  workflow_call:

jobs:
  go-vet:
    runs-on: ubuntu-latest
    steps:
      - name: Download source code artifact
        uses: actions/download-artifact@v3
        with:
          name: source-code

      - name: Extract source code
        run: tar -xzf source-code.tar.gz

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
          cache: true

      - name: Run go vet
        run: go vet ./...
