name: Terraform CI Lint

on:
  workflow_call:

jobs:
  terraform-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Download source code artifact
        uses: actions/download-artifact@v4
        with:
          name: source-code

      - name: Extract source code
        run: tar -xzf source-code.tar.gz

      - uses: actions/cache@v4
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint
        with:
          tflint_version: v0.52.0

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint Deployments
        run: |
          tflint --format compact --chdir configs --recursive

      - name: Run TFLint Configs
        run: |
          tflint --format compact --chdir configs --recursive

      - name: Run TFLint
        run: tflint
