name: Golang CI Lint

on:
  workflow_call:

jobs:
  lint-golang:
    runs-on: ubuntu-latest
    steps:
      - name: Download source code artifact
        uses: actions/download-artifact@v4
        with:
          name: source-code

      - name: Extract source code
        run: tar -xzf source-code.tar.gz

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
