name: Deploy eBay Listing Ingester
on:
  push
env:
  AWS_REGION : eu-west-2
permissions:
  id-token: write
  contents: read
jobs:
  validate_terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ['deployments/test', 'deployments/live'] }
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: false
        working-directory: ${{ matrix.dir }}

      - name: Terraform Init
        id: init
        run: terraform init
        continue-on-error: false
        working-directory: ${{ matrix.dir }}

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        continue-on-error: false
        working-directory: ${{ matrix.dir }}

      # - name: configure aws credentials
      #   uses: aws-actions/configure-aws-credentials@v3
      #   with:
      #     role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubOIDC
      #     role-session-name: OIDCRoleSession
      #     aws-region: ${{ env.AWS_REGION }}

      # - name: Terraform Plan
      #   id: plan
      #   run: terraform plan -no-color
      #   continue-on-error: false
