name: Deploy Control Alt Repeat
on:
  push
env:
  AWS_REGION : eu-west-2
permissions:
  id-token: write
  contents: read
jobs:
  main-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v3
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubOIDC
          aws-region: eu-west-2
          role-session-name: OIDCRoleSession      
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubOIDC
          aws-region: eu-west-2
          role-session-name: OIDCRoleSession

      - run: terraform fmt -check

      - run: terraform init
        working-directory: configs/test
      - run: terraform validate -no-color
        working-directory: configs/test
      - run: terraform plan -no-color
        working-directory: configs/test
      - run: terraform apply -auto-approve
        working-directory: configs/test

      - run: terraform init
        working-directory: configs/live
      - run: terraform validate -no-color
        working-directory: configs/live
      - run: terraform plan -no-color
        working-directory: configs/live
      - run: terraform apply -auto-approve
        working-directory: configs/live
