name: Deploy Control Alt Repeat
on:
  push
env:
  AWS_REGION : eu-west-2
permissions:
  id-token: write
  contents: read
jobs:
  validate_terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: false

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubOIDC
          role-session-name: OIDCRoleSession

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: configs/test
        continue-on-error: false

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: configs/test
        continue-on-error: false

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        working-directory: configs/test
        continue-on-error: false
