name: Deploy Control Alt Repeat
on:
  push
env:
  AWS_REGION : eu-west-2
permissions:
  id-token: write
  contents: read
jobs:
  MainPipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Build poc
        run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bootstrap ./cmd/aws/lambda/poc/main.go
      - uses: montudor/action-zip@v1
        with:
          args: zip lambda-handler-poc.zip bootstrap
      - name: Build poc-two
        run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bootstrap ./cmd/aws/lambda/poc-two/main.go
      - uses: montudor/action-zip@v1
        with:
          args: zip lambda-handler-poc-two.zip bootstrap
      - uses: hashicorp/setup-terraform@v3
      
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: false

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubOIDC
          aws-region: eu-west-2
          role-session-name: OIDCRoleSession

      - name: TEST Terraform Init
        id: init-test
        run: terraform init
        working-directory: configs/test
        continue-on-error: false

      - name: TEST Terraform Validate
        id: validate-test
        run: terraform validate -no-color
        working-directory: configs/test
        continue-on-error: false

      - name: TEST Terraform Plan
        id: plan-test
        run: terraform plan -no-color
        working-directory: configs/test
        continue-on-error: false

      - name: LIVE Terraform Init
        id: init-live
        run: terraform init
        working-directory: configs/live
        continue-on-error: false

      - name: LIVE Terraform Validate
        id: validate-live
        run: terraform validate -no-color
        working-directory: configs/live
        continue-on-error: false

      - name: LIVE Terraform Plan
        id: plan-live
        run: terraform plan -no-color
        working-directory: configs/live
        continue-on-error: false

      - name: TEST Terraform Deploy
        id: apply-test
        run: terraform apply -auto-approve
        working-directory: configs/test
        continue-on-error: false

      - name: LIVE Terraform Deploy
        id: apply-live
        run: terraform apply -auto-approve
        working-directory: configs/live
        continue-on-error: false